name: TorrServer
version: 1.0.2
slug: torr-server
description: Integration of TorrServer for home assistant
url: https://github.com/pkonshik/hass-addons
codenotary: pkonshik@gmail.com
webui: http://[HOST]:[PORT:8090]
init: false
arch:
  - aarch64
  - amd64
  - armv7
boot: manual
map:
  - share:rw
  - config:rw
options:
  ts_conf_path: "/config/torrserver/config"
  ts_log_path: "/share/torrserver/log"
  ts_torr_dir: "/share/torrserver/torrents"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ts_conf_path: str
  ts_log_path: str
  ts_torr_dir: str
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: TorrServer port
image: "ghcr.io/pkonshik/hass-addon-torrserver-{arch}"
host_network: true
panel_title: TorrServer
panel_icon: mdi:play-network
