build_from:
  aarch64: felddy/foundryvtt:release
  amd64: felddy/foundryvtt:release
args:
  BASHIO_VERSION: 0.15.0
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: FVTT Server"
  org.opencontainers.image.description: "Add-on to run fvtt on hass os."
  org.opencontainers.image.source: "https://github.com/pkonshik/hass-addons/fvtt"
  org.opencontainers.image.licenses: "MIT License"
