name: FVTT
version: 1.0.2
slug: fvtt-server
description: Integration of FVTT server for home assistant
url: https://github.com/pkonshik/hass-addons
codenotary: pkonshik@gmail.com
webui: https://[HOST]:[PORT:30000]
init: false
arch:
  - aarch64
  - amd64
boot: manual
map:
  - share:rw
  - media:rw
  - ssl
options:
  certfile: "/ssl/FoundryVTT.crt"
  keyfile: "/ssl/FoundryVTT.pem"
  ssl: true
  container_preserve_config: true
  foundry_vtt_data_path: "/media/BoardGame/data"
  container_cache: "/media/BoardGame/ContainerCache"
schema:
  certfile: str
  keyfile: str
  ssl: bool
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  container_preserve_config: bool
  foundry_vtt_data_path: str
  container_cache: str
ports:
  30000/tcp: 30000
ports_description:
  30000/tcp: FVTT server port
image: "pkonshik/hass-addon-fvtt-{arch}"
host_network: true
panel_title: FVTT
panel_icon: mdi:dice-d20
