name: FVTT
version: 1.0.1
slug: fvtt-server
description: Integration of FVTT server for home assistant
url: https://github.com/pkonshik/hass-addons
codenotary: pkonshik@gmail.com
webui: https://[HOST]:[PORT:30000]
init: false
arch:
  - aarch64
boot: manual
map:
  - share:rw
  - media:rw
  - ssl
environment:
  CONTAINER_PRESERVE_CONFIG: true
  FOUNDRY_DATA_DIR: /media/BoardGame/data
  CONTAINER_CACHE: /media/BoardGame/ContainerCache
  FOUNDRY_SSL_CERT: /ssl/FoundryVTT.crt
  FOUNDRY_SSL_KEY: /ssl/FoundryVTT.pem
ports:
  30000/tcp: 30000
ports_description:
  30000/tcp: FVTT server port
image: "ghcr.io/pkonshik/hass-addon-fvtt-{arch}"
host_network: true
panel_title: FVTT
panel_icon: mdi:dice-d20
